name: 2_unit_tests

on: [push]

jobs:

  unit-tests-in-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.7'

      - name: Install the dependencies
        run: pip install -r scripts/pipeline_2/requirements.txt

      - name: Run the tests
        run: pytest scripts/pipeline_2/tests.py
